### ISSUE TITLE
Expose GraphQL endpoint

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/open#14]
We ship microlink as microservice, where a request to `/` using `GET` is the only request allowed.

This is a simple and enough good way for consuming the service in major part of the use scenarios.

However, the microservice is growing and we found new problems:

- We can get a lot of information in the payload that could be not interesting for us.
- Every data field has a specific type defined (`date`, `author`, `link`, ...)
- Can't make more than one request in the same request.
- Apollo caching strategies are superior
- *[more excuse to use graphql here]*.

We want to explore the idea to ship a GraphQL endpoint at the main microlink endpoint.

The idea is put it under `/graphql` path and it do the same, but interacting with GraphQL.

**Examples**
- https://github.com/xxczaki/omdb-graphql-wrapper
- https://github.com/timneutkens/micro-apollo
- https://github.com/timneutkens/micro-graphql
- https://github.com/tylerbuchea/graphqless
- https://github.com/apollographql/apollo-link-rest

**Caching**
- https://spectrum.chat/graphql/general/how-do-you-cache-graphql-api-responses~847a1705-10a4-478c-81b3-83d638284956

**Exposing endpoint**
- `api.microlink.io/grapqhl`
- `api.microlink.io?grapqhl=true`
- `api.microlink.io/__grapqhl`
- request header `mode:graphql`

**Related**
- https://www.apollographql.com/docs/apollo-server/deployment/lambda.html
- https://blog.apollographql.com/layering-graphql-on-top-of-rest-569c915083ad
- https://www.yelp.com/developers/graphql/guides/basic_usage

**Comment by charsleysa** [comment]
@Kikobeats one limitation is that with GraphQL you cannot mix scalar types and object types.

For example, the `image` property returns a string by default but if you specify `palette` then it returns an object, in GraphQL you cannot define an `image` property that can return both.

You could work around this by always returning an object and just not have the extra information available unless you specify `palette`. 

Also, depending on how much extra processing is required, you could make `palette` an always on requirement for the GraphQL endpoint that only activates if you request `palette` specific properties.

E.g.
```
# does not activate palette
query {
  url(url:"https://example.com") {
    image {
      url
    }
  }
}

# activates palette
query {
  url(url:"https://example.com") {
    image {
      url
      color
      type
    }
  }
}
```

**Comment by Kikobeats** [comment]
Suggested API for using custom rules:

```graphql
query {
  url(url:"http://example.com") {
    myImage: typeImage(selectors:[{selector:"img", attr:"src"}]) {
      url
      color
      background_color
    }
  } 
}
```

**Comment by Kikobeats** [comment]
Although I implemented a preliminary version of this I decided to go steps back with that, since the vanilla old js version is enough for the same purpose and easy to connect with code
