### ISSUE TITLE
Kulturzentrum Faust

### ISSUE THREAD

**Issue by SusanneNussbaum** [microlinkhq/open#20]
## Bug Report

**Current Behavior**

{
"lang":"de"
"author":NULL
"title":"Veranstaltungen - Kulturzentrum Faust"
"publisher":"Kulturzentrum Faust"
"image":{
"url":"http://www.kulturzentrum-faust.de/imagetypes/img_teaser_h/linie6.jpg"
"width":480
"height":229
"type":"jpg"
"size":33001
"size_pretty":"33 kB"
"palette":[
0:"#4D4F45"
1:"#8A9C5A"
2:"#CCCCBB"
3:"#CFEC96"
4:"#6CB441"
5:"#3A6123"
]
"background_color":"#4D4F45"
"color":"#9ACF7B"
"alternative_color":"#CFEC96"
}
"description":NULL
"audio":NULL
"date":NULL
"video":NULL
"logo":{
"url":"https://logo.clearbit.com/www.kulturzentrum-faust.de?size=128&format=png"
"width":128
"height":128
"type":"png"
"size":5955
"size_pretty":"5.96 kB"
"palette":[
0:"#7C7C7C"
1:"#C4C4C4"
2:"#E54226"
3:"#F4BCAD"
4:"#444444"
5:"#761D0E"
]
"background_color":"#7C7C7C"
"color":"#FFFFFF"
"alternative_color":"#230904"
}
"url":"http://www.kulturzentrum-faust.de/veranstaltungen.html"
}

**Expected behavior/code**

I expect that the data from http://www.kulturzentrum-faust.de/veranstaltungen.html shows a list with the events from that club.

Example:
Name: "Das Teemännchen". Lesung
Date: 17.12.18
Entry: 19:00
Start: 20:00
Location: Pavillon

![faust](https://user-images.githubusercontent.com/45740918/49702260-81064b00-fbf6-11e8-975a-b35ee3f89d0c.PNG)

**Comment by Kikobeats** [comment]
Hello,

You need to use [Custom Rules](https://microlink.io/blog/custom-rules) for that purpose.

In addition, we are going to ship a new custom rules improvements soon – keep in touch if you subscribe to our [newsletter](https://microlink.us17.list-manage.com/subscribe/post?u=13504896341022a643b87c538&id=0d0978d452) 🙂
