### ISSUE TITLE
Retrieving information about image links does not work anymore.

### ISSUE THREAD

**Issue by DarkEnigma** [microlinkhq/open#22]
DESCRIPTION:
When we use the API to retrieve information about links, it can happen that a user links an image file. Just recently we noticed that it is not possible anymore to retrieve the image information from those directly linked images. Instead the request response only contains information about the favicon.

EXAMPLE:

```
https://api.microlink.io/?url=https://www.9skips.com/wp-content/uploads/2017/10/forests.jpg
```

delivers the response 

```json
{
  "status":"success",
  "data": {
    "lang":null,
    "author":null,
    "title":null,
    "publisher":null,
    "image":null,
    "description":null,
    "date":null,
    "logo": {
      "url":"https://www.9skips.com/favicon.ico",
      "width":16,
      "height":16,
      "type":"ico",
      "size":1150,
      "size_pretty":"1.15 kB"
    },
    "url":"https://www.9skips.com/wp-content/uploads/2017/10/forests.jpg"
  }
}
```

EXPECTED BEHAVIOR:
The response would contain the corresponding image information like before.

QUESTION:
Was this feature removed from the service or is this an actual bug? The main reason it is a problem because not every linked image contains a file ending like the link above. Otherwise it would be easier to filter for certain links before creating the corresponding link preview types in our application. We also tested custom rules as a possible solution but that also didn't work.

If you can provide any help or more detailed information I would really appreciate it.

**Comment by Kikobeats** [comment]
Hello @DarkEnigma, it is a not expected behavior; let me investigate a bit 🙂

**Comment by DarkEnigma** [comment]
That would be really nice, so thank you ^^

**Comment by Kikobeats** [comment]
Hello, we deployed this functionality back into API successful 🎉

**image**

```bash
https://api.microlink.io/?url=https://kikobeats.com/images/avatar-glitch.jpg
```

**video**

```bash
https://api.microlink.io/?url=https://microlink.io/preview.mp4&video
```

**audio**

```bash
https://api.microlink.io/?url=https://audiodemos.github.io/vctk_set0/embedadapt_100sample.wav&audio
```

Noted that for `video` and `audio` you need to provide the [API Parameter](https://docs.microlink.io/api/#api-parameters/audio) in order for enable this kind of detection.

Maybe that could be improved, just doing possible auto-detecting the field type based on the url extension? I'm not totally sure yet 🤔
